# Generated by Django 3.2.6 on 2021-08-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('produto',)},
        ),
    ]
