# Generated by Django 3.2.6 on 2021-08-20 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='mf',
            new_name='nf',
        ),
        migrations.AlterField(
            model_name='estoque',
            name='funcionario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
